name: 🚀 Deploy and Publish .Net WEBAPP on "Push"
on:
  push:
    branches:
      - 'main'
jobs:

  web-deploy:
    name: 🎉 Deploy and Publish
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v2
        
        - name: Setup .NET Core
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: '8.0'
            
        - name: Dotnet Publish
          run: dotnet publish . -c Release -nologo -v m
          
        - name: 🚚 Sync latest code to "Apache" webserver
          uses: easingthemes/ssh-deploy@main
          with:
            SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            ARGS: "-avzr --delete"
            REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
            REMOTE_USER: ${{ secrets.REMOTE_USER }}
            REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
            TARGET: ${{ secrets.REMOTE_TARGET }}
            EXCLUDE: ".git , .github"
            SCRIPT_AFTER: |
              systemctl reload apache2
              systemctl status apache2
