name: 🚀 Deploy and Publish .Net WEBAPP on "Push"
on:
  push:
    branches:
      - 'main'
jobs:

  web-deploy:
    name: 🎉 Deploy and Publish
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v2
        - name: Setup .NET Core
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: '8.0'
        - name: Dotnet Publish
          run: dotnet publish . -c Release -nologo -v m
        - name: Copy files via ssh rsync
          uses: trendyminds/github-actions-rsync@master
          with:
            RSYNC_OPTIONS: -avzr --delete --exclude node_modules --exclude '.git*'
            RSYNC_TARGET: ${{ secrets.REMOTE_TARGET }}
            RSYNC_SOURCE: /deploy/
          env:
            SSH_PRIVATE_KEY: ${{ secrets.REMOTE_SSH_KEY }}
            SSH_USERNAME: ${{ secrets.REMOTE_USER }}
            SSH_HOSTNAME: ${{ secrets.REMOTE_HOST }}
            SSH_PORT: ${{ secrets.REMOTE_PORT }}
        - name: Run SSH command
          uses: garygrossgarten/github-action-ssh@release
          with:
            command: sudo systemctl reload apache2
            host: ${{ secrets.REMOTE_HOST }}
            port: ${{ secrets.REMOTE_PORT }}
            username: ${{ secrets.REMOTE_USER }}
            privateKey: ${{ secrets.REMOTE_SSH_KEY }}
